<a href="https://colab.research.google.com/github/feracor/Curso-de-Algebra-Lineal-Aplicada-para-Machine-Learning/blob/main/Algebra_Lineal_Aplicada_para_Machine_Learning.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **2- Podemos y debemos pensar a las matrices como transformaciones lineales**


In [2]:
%matplotlib inline    
import numpy as np
import matplotlib as plt

In [4]:
A = np.array([[-1,3],[2,-2]])
A

array([[-1,  3],
       [ 2, -2]])

In [5]:
vector = np.array([[2],[1]])
vector

array([[2],
       [1]])

In [6]:
def graficarVectores(vecs, cols, alpha = 1):
  plt.axvline(x = 0, color = 'grey', zorder = 0)
  plt.axhline(y = 0, color = 'grey', zorder = 0)

  for i in range(len(vecs)):
    x =  np.concatenate([[0,0], vecs[i]])
    plt.quiver ([x[0]],
                [x[0]],
                [x[0]],
                [x[0]],
                angles = 'xy', scale_units = 'xy',
                alpha = alpha)

In [8]:
print(vector)
print(vector.flatten())

[[2]
 [1]]
[2 1]


In [9]:
print(A)
print(A.flatten())

[[-1  3]
 [ 2 -2]]
[-1  3  2 -2]
